version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/prototypey"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/site"
    schedule:
      interval: "weekly"
