jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Build site
        run: pnpm -F @prototypey/site build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: prototypey
          directory: packages/site/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

name: Deploy

on:
  push:
    branches:
      - main
  pull_request: